MITLibraries/slingshot

slingshot/cli.py, tests/test_cli.py
=> Add log messages layer submission result

slingshot/__init__.py, slingshot/app.py, slingshot/cli.py, tests/test_app.py
This should live further up the stack.
=> Move exception catching out of prep_bag

slingshot/app.py, tests/test_app.py
Use content negotiation when requesting status.
=> Request application/json when getting status

slingshot/app.py, slingshot/cli.py, tests/test_app.py
This adds support for loading a single layer or a directory of layers.
=> Support single layer or directory of layers

.travis.yml, Makefile, Pipfile, Pipfile.lock, slingshot/app.py, slingshot/db.py
This switches to using pipenv and Pipfile to manage dependencies.
Support for python 3 has been re-enabled.
=> Add Pipfile and pipenv

Pipfile, Pipfile.lock, slingshot/app.py, slingshot/parsers.py, slingshot/record.py, tests/test_record.py
This is the only place this code is being used now. Just bringing it
here to simplify things.
=> Remove ogre dependency

slingshot/app.py
Some of these things are 10GB+. Takes forever to read.
=> Stream zipfile contents when unpacking

slingshot/app.py, slingshot/cli.py, tests/test_app.py, tests/test_cli.py
This adds a reindex function to the CLI for reloading the index when
metadata has changed.
=> Add reindex function

slingshot/app.py
The `pyshp` package doesn't close any of the opened files in the Reader.
This subclasses the Reader object and adds a context manager interface.
=> Use context manager for shapefile reader

.travis.yml, Makefile, README.md, slingshot/app.py, slingshot/cli.py, tests/conftest.py, tests/unit/test_cli.py, tox.ini
Adds support for copying FGDC to a web accessible location.
=> Add metadata copying

.travis.yml, tox.ini
This drops support for 2.7 and switches support for 3.5 to 3.6.
=> Drop 2.7, switch to 3.6

slingshot/app.py
Some data layers can legitimately contain more than one XML file. We
need to be able to differentiate between them in order to locate the
FGDC metadata. This provides some basic support to do this. A more
robust implementation should incrementally parse the beginning of an XML
file to find the root element.
=> Correctly handle layers with multiple XML files

Pipfile, Pipfile.lock, setup.py, slingshot/cli.py, slingshot/marc.py, slingshot/record.py, tox.ini
This adds a new command for parsing and indexing records from MARC XML.
The new `marc` command will delete all existing MARC records from the
index and then reindex from a given file.
=> Add MARC XML indexing

slingshot/app.py, slingshot/cli.py, slingshot/layer.py
This adds support for using minio instead of S3 for GeoTiffs.
There's no real way to test this until the docker compose file for GeoWeb is finished.
=> Add support for minio

slingshot/app.py, slingshot/cli.py, tests/test_cli.py
This adds an initialize command that will create the necessary
workspaces and PostGIS datastores in GeoServer.
=> Add GeoServer initialization command

slingshot/cli.py, tests/test_cli.py
This adds documentation for the publish subcommand. In addition, it adds
environment variable configuration for the --s3-endpoint and --s3-alias
options.
=> Update CLI docs for publish command

slingshot/app.py, slingshot/cli.py, tests/test_cli.py
This sets up layer security for GeoServer during initialization.
=> Add GeoServer security config to initialization

doc/adr/0001-record-architecture-decisions.md, doc/adr/0002-use-upload-and-storage-s3-buckets.md
I need to start tracking the weird decisions made for this project.
=> Add ADR for S3 buckets

slingshot/app.py, slingshot/cli.py, tests/test_app.py
This partially addresses #99. There are other places in the codebase
that need the region specified, but this fixes the worst offender.
=> Partially fixes region/endpoint problem

slingshot/db.py
A handful of layers are using field type F instead of N.
=> Add field type F to shapefile fields

slingshot/marc.py
These letters are magic. I hope this is right.
=> Filter MARC records based on status
