MITLibraries/slingshot

- slingshot/app.py
- tests/test_app.py
The uuid module differs in support for unicode between python 2 and
3. This should correctly handle either unicode or byte strings.
> Add support for unicode when creating uuid

- slingshot/app.py
- tests/test_app.py
The shapefile archives need to be flat or GeoServer won't load the
data.
> Move files in archive to top level directory

- slingshot/cli.py
- tests/test_cli.py
Closes #9. Provides an option to set the number of consecutive
failures allowed before the script stops execution.
> Stop execution after specified number of failures

- .travis.yml
- slingshot/app.py
- tests/test_app.py
- tox.ini
Slingshot will overwrite a bag with the same name in the store. The
assumption is that the layer names are static and we always want the
most recent version.
> Overwrite existing bag in store

- slingshot/app.py
- slingshot/cli.py
- tests/test_app.py
- tests/test_cli.py
Rather than throwing an exception for existing layers, this will now
just skip them and print a message about doing so.
> Skip existing layers

- .bumpversion.cfg
- .gitignore
- .travis.yml
- Makefile
- Pipfile
- Pipfile.lock
- setup.cfg
- setup.py
- tox.ini
This (hopefully) provides a better process for testing, allowing tox to
isolate the test environment and pipenv to manage the dependencies.
There doesn't seem to be a clean way to test python 2/3 with pipenv, so
hashes have been removed from the Pipefile.lock for now.
> Clean up build/test process

- slingshot/app.py
- slingshot/db.py
- tests/test_db.py
This replaces the tempfile approach to a streaming interface to the
shapefile. The PGShapeReader can be passed to psycopg2's copy_from
method on the cursor object.
> Add streaming reader for Postgres COPY

- tox.ini
A recent change to pipenv means this is no longer necessary. It will
detect it is being run in a virtualenv created by tox and just install
dependencies into that.
> Remove the system install from tox

- setup.py
- slingshot/__init__.py
- slingshot/app.py
- slingshot/cli.py
- slingshot/parsers.py
- slingshot/record.py
- tests/conftest.py
- tests/integration/test_command_line.py
- tests/unit/test_app.py
We're no longer supporting Python 2. This mostly just removes some
boiler plate that's no longer required, with a few changes having to do
with strings vs bytes.
Closes #45.
> Remove Python 2 cruft

- .travis.yml
- tests/integration/test_command_line.py
- tox.ini
Pipenv now includes flake8 and dotenv loading by default, so we no
longer need to specify these as dependencies. This also adds a tox
environment for running the new safety check feature in Pipenv. CI
builds will fail if any security problems are discovered in third party
dependencies.
> Use new pipenv features

- slingshot/parsers.py
The old keywords (theme and place) are still in the FGDC metadata. The
new keywords, I think, should all have a urn attribute pointing to a
worldcat fast resource. The parser will now ignore any keyword without a
urn.
> Only use keywords with urn

- Pipfile
- Pipfile.lock
- slingshot/app.py
- slingshot/record.py
- tests/unit/test_app.py
- tests/unit/test_record.py
The old record object was difficult to maintain and easy to break. This
has been replaced with an object based off of the third party `attrs`
module. This new record requires slightly more effort to use, but it's
much more difficult to misuse or make mistakes while modifying.
The implementation itself provides an almost entirely similar interface
for creation. The main differences are:
* Immutability; it is no longer possible to change a field once the
record has been created. (It's still possible to modify mutable fields
like dictionaries or lists.)
* Datetime fields must be correctly formatted before creation.
* The `solr_geom` field should be assembled before creating the record.
> Refactors the record object

- .travis.yml
- slingshot/app.py
- slingshot/db.py
- tests/integration/test_command_line.py
This adds support for putting the data layers into a separate PG schema.
It's a bit of a hack in its current state as the schema is hard coded as
``geodata``. This will need to be fixed to make it configurable. The
tests will also need to be updated to reflect this change.
The addition of schema support is necessary because both the spatial
data and the Rails app currently share the same table space. The better
approach will be to pull them out into separate spaces.
> Add support for PG schemas

- slingshot/db.py
A backslash itself needs to be escaped when generating the Postgres copy
output.
> Add backslash to quotable characters

- slingshot/cli.py
This was preventing the metadata link from showing up in GeoBlacklight.
> Remove trailing slash from FGDC URI

- slingshot/app.py
This will put the download copy of the TIFFs into a public/secure
subdirectory of the specified download directory.
> Add sub dir for TIFF directory

- slingshot/app.py
This switches to incremental parsing to try and determine whether or not
an XML file is an FGDC XML file. Any XML file whose first element is
`metadata` should pass now.
> Use more reliable test for FGDC

- slingshot/app.py
Use the correct URL for the location of the TIFF download.
> Fix TIFF URL

- tox.ini
Closes #69. The problematic packages seem to have fixed themselves. A
crisis has been averted, and the world once again rests firmly upon its
axis.
> Revert pip downgrade

- slingshot/cli.py
This assumes that the existence of an FGDC metadata file in the metadata
directory means a layer is already published. Under normal operation
this assumption should be true. The alternative would be to also check
whether the layer exists in GeoServer and Solr, but this would result in
thousands of HTTP requests.
> Skip already published layers

- Dockerfile
- Makefile
- setup.py
This adds a Dockerfile for building the image. The wheel packaging step
has been moved into a docker stage for more consistency in the
build/deploy pipeline.
The git versioning for the app has been removed. It was always kind of
fragile and is more work to do in the container than it's probably
worth. git versions will be applied to the container tag during the
continuous integration process, so versioning will be managed at the
container level.
> Add docker build

- README.md
- setup.py
- slingshot/cli.py
- slingshot/db.py
- tests/test_cli.py
- tests/test_db.py
Closes #61. This adds a `--db-schema` command line option and a matching
`PG_SCHEMA` envvar. The schema defaults to `public`.
> Make PostGres schema configurable at runtime

- slingshot/app.py
This will default to forcing a soft commit after adding each layer. This
is unlikely to have any noticeable impact in normal production usage but
will make local development easier as the results will be immediately
visible.
> Use soft commits when adding documents

- Pipfile
- README.md
This makes use of the scripts section in Pipfile to allow running
slingshot without having installed it into the virtualenv. The preferred
production deployment will still be to install slingshot as a package
but the Pipfile should be fine for local development.
> Add scripts section to Pipfile

- .travis.yml
- Makefile
This sets up the automated deploy process from Travis. A new container
will be pushed to the staging container registry. Promoting to
production will still require manually running `make promote`.
> Add automated deploy

- slingshot/app.py
- slingshot/cli.py
- tests/test_app.py
The publishing command will likely use multiple threads and most
information I can find online seems to agree that the requests.Session
object is not threadsafe.
> Make GeoServer and Solr clients threadsafe

- slingshot/app.py
- slingshot/layer.py
- slingshot/s3.py
This adds a singleton boto3 session class to deal with the fact that the
boto3 session isn't threadsafe. It's a little gross but given that boto3
is used throughout, just dumping it into a global thread local seems
like the least worst option.
> Make boto3 session threadsafe

- slingshot/__init__.py
- slingshot/app.py
- slingshot/cli.py
- tests/conftest.py
- tests/test_app.py
- tests/test_cli.py
- tox.ini
This changes the publish command to support publishing multiple layers
either by specifying the uploaded layer names as arguments or by using
the new `--publish-all` switch. If using the latter, this will scan the
upload bucket and publish all layers it finds. If a layer has already
been published it will be skipped if the published layer is newer than
the uploaded layer.
Rudimentary information about a layer's state is managed in a DynamoDB
table.
> Support publishing multiple layers at once

- slingshot/app.py
- tests/conftest.py
- tests/test_app.py
- tests/test_cli.py
The FGDC file for each layer should be made public, regardless of
whether or not the layer itself is restricted. This adds a step during
the publishing process to change the ACL to public read on the FGDC file
as well as adding the necessary link to the file in the GeoBlacklight
record.
> Make FGDC publicly available in S3

- doc/adr/0003-use-one-geoserver-instance-with-multiple-workspaces.md
This affects both our Geoblacklight instance and slingshot, but I'm
publishing here because ADRs are already set up.
> Add ADR for GeoServer authentication setup

- slingshot/cli.py
Some of the exceptions that can be raised during processing of a layer
aren't particularly helpful. This will also print the traceback for any
exceptions.
> Add traceback information to failed layers

- slingshot/app.py
- slingshot/cli.py
- tests/test_app.py
- tests/test_cli.py
The proxy URL for WMS/WFS needs to be written to the Geoblacklight
record instead of the URL for GeoServer.
> Add OGC proxy URL

- slingshot/cli.py
ECS claims to send both stdout and stderr to Cloudwatch, but this is so
far not my experience. Going to try printing the traceback info to
stdout instead.
> Print traceback information to stdout

- Pipfile.lock
- pytest.ini
- slingshot/__init__.py
- slingshot/app.py
- slingshot/db.py
- slingshot/s3.py
- tests/conftest.py
The S3IO wrapper class that was needed to make an S3 object function
like a file led to some pretty bad performance problems. An object was
read in most cases at no more than 8192 bytes at a time. As you can
imagine, this is not an efficient way to read a large file over the
network.
These changes switch to using multipart uploads for S3 and manually
request chunks of the file at a specified chunk size when reading the
zipfile. The Wrapper class that inherits from BufferedIOBase is a shim
for loading the shapefile into Postgres because it's not possible to
control the buffering otherwise.
The S3_BUFFER_SIZE constant controls how much is requested from S3 at a
time. Keep in mind you will likely see an increase in memory consumption
equal to roughly this number times however many worker …
> Fix S3 read/write performance issues

- Dockerfile
- entrypoint.sh
- setup.py
It turns out ECS can frequently discard the logs before fully flushing
them to Cloudwatch. This was supposedly fixed recently but my experience
suggests otherwise. This adds a 10 second pause after slingshot has
exited before fully exiting the container. It seems to be enough to
ensure that all the slingshot logs are written to Cloudwatch.
> Wait for ECS to flush logs

- .travis.yml
- Pipfile.lock
- slingshot/cli.py
- slingshot/db.py
This fixes an encoding problem with several layers. I've also disabled coveralls for now because it appears to be broken.
> Add encoding to Shapefile reader

- .travis.yml
- slingshot/db.py
- slingshot/s3.py
This fixes a few problems with the S3IO wrapper. These changes make it
possible to use the `io.BufferedReader` for the different files in the
Shapefile when loading into Postgres. Memory usage should now be fully
capped and largely controlled by the number of worker threads and size
of the `S3_BUFFER_SIZE` constant.
>  Use io.BufferedReader for Postgres COPY 

- slingshot/marc.py
- slingshot/record.py
This fixes a bug that caused the process to endlessly loop, making
failed requests to S3. The MARC parser will now raise an exception for
anything except for an encoding problem.
It also changes the bounding box validator to allow points.
> Exit if parsing fails

- slingshot/cli.py
- slingshot/marc.py
- tests/test_marc.py
Updates the MARC parser to correctly parse and ingest Alma records into Geoweb. This includes:
- Fixing a record parsing bug in the MARC parser that was presumably there to handle poorly structured MARC records from Aleph
- Updating the source record URL to point to Primo for Alma records
- Updating the CLI `marc` command to enable local testing against the Geoweb dev environment
- Updating tests
So...this is not simple. However, it is possible. The [geoweb repository](https://github.com/mitlibraries/geoweb) has instructions for setting up a local Geoweb dev environment using docker-compose. You can do that (following all the instructions carefully), upload an Alma record export (see dip-stage s3 bucket) to the local Minio upload folder, and then run the slingshot command `pipenv run …
> Alma updates

- Makefile
- slingshot/marc.py
- slingshot/record.py
- tests/test_marc.py
The record publication date field was processed into JSON as an array instead of a string, which resulted in very strange dates in the Geoblacklight view. The dates also include some odd characters that are correct for MARC cataloging but that we don't want to display.
* Changs the record date field (dct_temporal_sm) to a string instead of an array
* Strips brackets and other cataloging characters
year string before ingesting
* Also updates the Makefile to use new AWS CLI login command
None, but Slingshot will need to be re-run after merge with the latest full export from Alma.
> Fix bug in MARC parser, update Makefile
